// this array holds each slideshow slides content with img src and id
let slideShowData = [
    {
        id: "sHImg001",
        src: "src/images/test-image-003.jpg"
    },
    {
        id: "sHImg002",
        src: "src/images/test-image-001.jpg"
    },
    {
        id: "sHImmg003",
        src: "src/images/test-image-002.jpg"
    }
]
let products= [
    {
        id: "LMProMNEP3",
        title: "Macbook pro MNEP3 2022 لپ تاپ اپل مدل",
        price: 40790000,
        brand:"apple",
        img: "src/images/laptop/LMProMNEP3.jpg",
        discount: 0,
        inventoryNumbers: 10,
        CPU: "M2",
        RAM: "8GB",
        screenSize: "13 inch",
        addtionalDesc:"",
        geranti: "هجده ماهه پیکسل",
        rate: 4.3,
    },
    {
        id: "LMProMK193",
        title: "MacBook Pro MK193 2021 لپ تاپ اپل مدل",
        price: 81700000,
        brand:"apple",
        img: "src/images/laptop/LMProMK193.jpg",
        discount: 5,
        inventoryNumbers: 5,
        CPU: "M1",
        RAM: "16GB" ,
        screenSize: "16.2 inch",
        addtionalDesc: "",
        geranti: "یکساله پیکسل",
        rate: 4.8,
    },
    {
        id: "LMProMYDA2",
        title: "MacBook Pro MYDA2 2020 لپ تاپ اپل مدل ",
        price: 39190000,
        brand:"apple",
        img: "src/images/laptops/LMProMYDA2.jpg",
        discount: 0,
        inventoryNumbers: 13,
        CPU: "M1",
        RAM: "8GB",
        screenSize: "13.3 inch",
        addtionalDesc: "",
        geranti: "شش ماهه پیکسل",
        rate: 4.2,
    },
    {
        id: "LAX543MA-GQ1012",
        title: "X543MA-GQ1012 اینچی ایسوس مدل ",
        price: 5900000,
        brand:"asus",
        img: "src/images/laptops/LAX543MA-GQ1012.jpg",
        discount: 0,
        inventoryNumbers: 0,
        CPU: "Celeron",
        RAM: "4GB",
        screenSize: "15.6 inch",
        addtionalDesc: "",
        geranti: "بدون گارانتی",
        rate: 3.9,
    },
    {
        id: "LAVivoBookR565JP-EJ378",
        title: "X543MA-GQ1012 اینچی ایسوس مدل ",
        price: 18690000,
        brand:"asus",
        img: "src/images/laptops/LAVivoBookR565JP-EJ378.jpg",
        discount: 5,
        inventoryNumbers: 7,
        CPU: "Core i7",
        RAM: "8GB",
        screenSize: "15.6 inch",
        addtionalDesc: "",
        geranti: "دو ساله سازگار",
        rate: 3.9,
    },
    {
        id: "LAX515JP-EJ007WY",
        title: "LAX515JP-EJ007WY لپ تاپ ایسوس مدل",
        price: 18690000,
        brand:"asus",
        img: "src/images/laptops/LAX515JP-EJ007WY.jpg",
        discount: 16,
        inventoryNumbers: 3,
        CPU: "Core i7",
        RAM: "20GB",
        screenSize: "15.6 inch",
        addtionalDesc: "",
        geranti: "دو ساله سازگار",
        rate: 4.9,
    },
    {
        id: "LHG7-250-A",
        title: "G7-250-A لپتاپ اج پی",
        price: 11750000,
        brand:"HP",
        img: "src/images/laptops/LHG7-250-A.jpg",
        discount: 0,
        inventoryNumbers: 3,
        CPU: "Core i3",
        RAM: "8GB",
        screenSize: "15.6 inch",
        addtionalDesc: "",
        geranti: "دو ساله سازگار",
        rate: 4.9,
    },
    {
        id: "LH255G7-R3B",
        title: "255 G7-R3B لپتاپ اج پی",
        price: 11750000,
        brand:"HP",
        img: "src/images/laptops/LHG7-250-A.jpg",
        discount: 0,
        inventoryNumbers: 3,
        CPU: "Ryzen 3",
        RAM: "8GB",
        screenSize: "15.6 inch",
        addtionalDesc: "",
        geranti: "دو ساله سرپر",
        rate: 3.4,
    }
]
let additionalInfoData = [
    {
        id:"AID خرید اقساطی",
        title:"خرید اقساطی",
        iconClass:"bi bi-credit-card",
    },
    {
        id:"AID ارسال رایگان",
        title:"ارسال رایگان",
        iconClass:"bi bi-truck",
    },
    {
        id:"AID پاسحگویی ۲۴ ساعته",
        title:"پاسحگویی ۲۴ ساعته",
        iconClass:"bi bi-mic",
    },
    {
        id:"AID تحویل کمتر از ۳ روز",
        title:"تحویل کمتر از ۳ روز",
        iconClass:"bi bi-calendar2-check",
    }
]